[2024-05-06T14:40:14.235+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T14:20:00+00:00 map_index=10 [queued]>
[2024-05-06T14:40:14.333+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T14:20:00+00:00 map_index=10 [queued]>
[2024-05-06T14:40:14.334+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 4
[2024-05-06T14:40:14.418+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-06 14:20:00+00:00
[2024-05-06T14:40:14.454+0000] {standard_task_runner.py:60} INFO - Started process 810022 to run task
[2024-05-06T14:40:14.526+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-06T14:20:00+00:00', '--job-id', '35813', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpurqas5p4', '--map-index', '10']
[2024-05-06T14:40:14.530+0000] {standard_task_runner.py:88} INFO - Job 35813: Subtask ETL_job
[2024-05-06T14:40:14.819+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-06T14:20:00+00:00 map_index=10 [running]> on host a09da322e808
[2024-05-06T14:40:15.288+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T14:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T14:20:00+00:00'
[2024-05-06T14:40:15.292+0000] {Units_dag.py:99} INFO - i: 100000, chunk: 10000
[2024-05-06T14:40:15.292+0000] {Units_dag.py:100} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MDA2NDAzLCJleHAiOjE3MTc1OTg0MDMsIm5iZiI6MTcxNTAwNjQwMywianRpIjoiUkZ0OVcyejFFYnVyMDlJNSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.0nWLIhKxvYZFnl9pkZr-qEJ-F1ui391e3WxtgyYFxMg
[2024-05-06T14:40:42.800+0000] {Units_dag.py:104} INFO - {'_id': '6456106e43123950261a8f14', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'measurement_type': 'count', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '5966 V R A', 'operation_code': None, 'device_gateway': None, 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '860665057589235', 'sim_number': '+966830032419102', 'sim_serial': '8996609821111914810', 'device_serial': '860665057589235', 'device': 'bce', 'user_id': '63db640e9c8ad412585c9626', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2023-05-06 11:31:42', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'sedo-alwatania-admin', 'last_update': {'dtt': 1715006316000, 'dts': 1715006329844, 'spd': 0, 'ang': 150, 'alt': 605, 'chPrams': {'ePwrV': {'v': 25.763, 'cdt': 1715006316000}, 'di16': {'v': 1, 'cdt': 1713770428000}, 'rssi1': {'v': 21, 'cdt': 1715006016000}, 'di15': {'v': 0, 'cdt': 1710356540000}, 'di14': {'v': 0, 'cdt': 1715005586000}, 'di13': {'v': 0, 'cdt': 1713770428000}, 'di12': {'v': 0, 'cdt': 1713770428000}, 'di11': {'v': 0, 'cdt': 1713770428000}, 'di10': {'v': 0, 'cdt': 1713770428000}, 'di2': {'v': 1, 'cdt': 1713777504000}, 'ai4': {'v': 11917, 'cdt': 1715006316000}, 'di1': {'v': 0, 'cdt': 1715005716000}, 'di4': {'v': 0, 'cdt': 1713770428000}, 'di3': {'v': 0, 'cdt': 1713770428000}, 'di6': {'v': 0, 'cdt': 1713770428000}, 'di5': {'v': 0, 'cdt': 1715005716000}, 'lac1': {'v': 1202, 'cdt': 1715004562000}, 'di8': {'v': 1, 'cdt': 1713777504000}, 'protocol': {'v': 'bce', 'cdt': 1713770428000}, 'di7': {'v': 0, 'cdt': 1715006016000}, 'di9': {'v': 0, 'cdt': 1713770428000}, 'iPwrV': {'v': 4.079, 'cdt': 1715005706000}, 'cid1': {'v': 6913, 'cdt': 1715005616000}, 'odometer': {'v': 0, 'cdt': 1715005616000}, 'spd': {'v': 0, 'cdt': 1715005586000}, 'sat': {'v': 12, 'cdt': 1715002570000}, 'hdop': {'v': 1, 'cdt': 1715002062000}, 'ta': {'v': 0, 'cdt': 1713770428000}, 'mcc1': {'v': 420, 'cdt': 1714569026000}, 'mnc1': {'v': 3, 'cdt': 1714569026000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 12, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 0, 'ePwrV': 25.763, 'ai4': 11917, 'iPwrV': 4.079, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 1202, 'cid1': 6913, 'rssi1': 21}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'di16': 1, 'ePwrV': 25.879, 'di15': 0, 'rssi1': 21, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di2': 1, 'di1': 0, 'ai4': 12103, 'di4': 0, 'di3': 0, 'di6': 0, 'di5': 0, 'lac1': 1202, 'protocol': 'bce', 'di8': 1, 'di7': 0, 'di9': 0, 'iPwrV': 4.079, 'cid1': 6913, 'odometer': 0, 'spd': 0, 'sat': 12, 'hdop': 1, 'ta': 0, 'mcc1': 420, 'mnc1': 3}, 'vLoc': 1, 'vCon': 1, 'ip': '37.216.48.39', 'rl': 0, 'trl': 17491.7788, 'mdu': 0, 'tmdu': 1249204, 'eidl': 0, 'teidl': 1385298, 'fc': 0, 'tfc': 10.890276, 'acc': 0, 'accOn': 29585364, 'accOff': 15322236, 'sdu': 300, 'tsdu': 600, 'lat': 24.74503517150879, 'lng': 46.831634521484375}, 'counters': {'odometer_type': 'gps', 'odometer': 26517.7542, 'engine_hours_type': 'acc', 'engine_hours': 29585364, 'last_acc': 0}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-06T14:40:44.538+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T14:40:44.689+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T14:40:44.835+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-06T14:40:44.858+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T14:40:44.944+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.107s]
[2024-05-06T14:40:45.763+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-06T14:40:45.916+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.187s]
[2024-05-06T14:40:46.517+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 112, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-06T14:40:46.532+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=10, execution_date=20240506T142000, start_date=20240506T144014, end_date=20240506T144046
[2024-05-06T14:40:46.555+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 35813 for task ETL_job (10000 document(s) failed to index.; 810022)
[2024-05-06T14:40:46.637+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-06T14:40:46.664+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
