[2024-05-07T19:23:09.994+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T19:00:00+00:00 map_index=6 [queued]>
[2024-05-07T19:23:10.007+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T19:00:00+00:00 map_index=6 [queued]>
[2024-05-07T19:23:10.008+0000] {taskinstance.py:2193} INFO - Starting attempt 3 of 4
[2024-05-07T19:23:10.028+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-07 19:00:00+00:00
[2024-05-07T19:23:10.035+0000] {standard_task_runner.py:60} INFO - Started process 842249 to run task
[2024-05-07T19:23:10.045+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-07T19:00:00+00:00', '--job-id', '39635', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpmum5yhs5', '--map-index', '6']
[2024-05-07T19:23:10.047+0000] {standard_task_runner.py:88} INFO - Job 39635: Subtask ETL_job
[2024-05-07T19:23:10.132+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-07T19:00:00+00:00 map_index=6 [running]> on host a09da322e808
[2024-05-07T19:23:10.308+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-07T19:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-07T19:00:00+00:00'
[2024-05-07T19:23:10.309+0000] {Units_dag.py:98} INFO - i: 60000, chunk: 10000
[2024-05-07T19:23:10.309+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1MTA5NjA0LCJleHAiOjE3MTc3MDE2MDQsIm5iZiI6MTcxNTEwOTYwNCwianRpIjoiTmEyYUdWT0FTSnNkTXB0OSIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.yzPM_UquVVUj9oW4HlwRf7JMc_jDuUKlqCErdvJONDU
[2024-05-07T19:23:26.484+0000] {Units_dag.py:103} INFO - {'_id': '63300f43389e52091b059f28', 'icon': 'icons/icon.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '8347HUD', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '866854059852171', 'sim_number': '+966830020187981', 'sim_serial': '996641520415680044', 'device_serial': '866854059852171', 'device': 'bce', 'user_id': '631f42b9592ec620f242907f', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-09-25 11:20:19', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'mohamed-elsafi-group-admin', 'last_update': {'dtt': 1715109588000, 'dts': 1715109637488, 'spd': 0, 'ang': 260, 'alt': 65526, 'chPrams': {'ePwrV': {'v': 12.759, 'cdt': 1715109588000}, 'di16': {'v': 1, 'cdt': 1714820778000}, 'rssi1': {'v': 56, 'cdt': 1715108998000}, 'di15': {'v': 0, 'cdt': 1714820778000}, 'di14': {'v': 0, 'cdt': 1715105078000}, 'di13': {'v': 0, 'cdt': 1714820778000}, 'di12': {'v': 0, 'cdt': 1714820778000}, 'di11': {'v': 0, 'cdt': 1714820778000}, 'di10': {'v': 0, 'cdt': 1664104870000}, 'di2': {'v': 0, 'cdt': 1714728546000}, 'di1': {'v': 0, 'cdt': 1715105146000}, 'ai4': {'v': 28210, 'cdt': 1715109588000}, 'di4': {'v': 0, 'cdt': 1714728546000}, 'di3': {'v': 0, 'cdt': 1714820778000}, 'di6': {'v': 0, 'cdt': 1715105146000}, 'di5': {'v': 0, 'cdt': 1715105146000}, 'lac1': {'v': 3719, 'cdt': 1715095180000}, 'protocol': {'v': 'bce', 'cdt': 1714820778000}, 'di8': {'v': 1, 'cdt': 1714820778000}, 'di7': {'v': 0, 'cdt': 1715105146000}, 'di9': {'v': 0, 'cdt': 1714820778000}, 'iPwrV': {'v': 4.108, 'cdt': 1715107516000}, 'cid1': {'v': 20931, 'cdt': 1715105100000}, 'odometer': {'v': 1058948829, 'cdt': 1715109588000}, 'spd': {'v': 0, 'cdt': 1715105116000}, 'sat': {'v': 15, 'cdt': 1715107812000}, 'hdop': {'v': 1, 'cdt': 1714357190000}, 'ta': {'v': 0, 'cdt': 1714820778000}, 'mcc1': {'v': 420, 'cdt': 1715095180000}, 'mnc1': {'v': 3, 'cdt': 1715095180000}}, 'prms': {'protocol': 'bce', 'spd': 0, 'sat': 15, 'hdop': 1, 'odometer': 1058948829, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 0, 'ePwrV': 12.759, 'ai4': 28210, 'iPwrV': 4.108, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 3719, 'cid1': 20931, 'rssi1': 56}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'protocol': 'bce', 'spd': 0, 'sat': 15, 'hdop': 1, 'odometer': 0, 'di16': 1, 'di15': 0, 'di14': 0, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 0, 'di6': 0, 'di5': 0, 'di4': 0, 'di3': 0, 'di2': 0, 'di1': 0, 'ePwrV': 12.83, 'ai4': 28230, 'iPwrV': 4.108, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 3719, 'cid1': 20931, 'rssi1': 56}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.81.61', 'rl': 0, 'trl': 8547.7907, 'mdu': 0, 'tmdu': 728166, 'eidl': 0, 'teidl': 440582, 'fc': 0, 'tfc': 20.556456, 'acc': 0, 'accOn': 792707478, 'accOff': 4812942722, 'sdu': 296, 'tsdu': 4442, 'lat': 26.973777770996094, 'lng': 49.649696350097656}, 'counters': {'odometer_type': 'gps', 'odometer': 8547.7907, 'engine_hours_type': 'acc', 'engine_hours': 792707478, 'last_acc': 0}, 'is_wasl_connected': 'Not Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/icon.png', 'hasCCTV': False}
[2024-05-07T19:23:27.004+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T19:23:27.048+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T19:23:27.099+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-07T19:23:27.132+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T19:23:27.191+0000] {_transport.py:335} INFO - GET https://dbelk1.afaqy.local:9200/_cluster/health [status:200 duration:0.088s]
[2024-05-07T19:23:27.569+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T19:23:27.582+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.033s]
[2024-05-07T19:23:27.583+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk2.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-07T19:23:27.583+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-07T19:23:27.584+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk1.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-07T19:23:27.746+0000] {_transport.py:335} INFO - PUT https://dbelk1.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:0.162s]
[2024-05-07T19:23:28.092+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 10000 document(s) failed to index.
[2024-05-07T19:23:28.112+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=6, execution_date=20240507T190000, start_date=20240507T192309, end_date=20240507T192328
[2024-05-07T19:23:28.142+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 39635 for task ETL_job (10000 document(s) failed to index.; 842249)
[2024-05-07T19:23:28.192+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-07T19:23:28.227+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
