[2024-05-11T06:06:14.396+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-11T05:40:00+00:00 map_index=6 [queued]>
[2024-05-11T06:06:14.413+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-11T05:40:00+00:00 map_index=6 [queued]>
[2024-05-11T06:06:14.414+0000] {taskinstance.py:2193} INFO - Starting attempt 4 of 4
[2024-05-11T06:06:14.434+0000] {taskinstance.py:2217} INFO - Executing <Mapped(_PythonDecoratedOperator): ETL_job> on 2024-05-11 05:40:00+00:00
[2024-05-11T06:06:14.442+0000] {standard_task_runner.py:60} INFO - Started process 933427 to run task
[2024-05-11T06:06:14.448+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Units_statistics_DAG', 'ETL_job', 'scheduled__2024-05-11T05:40:00+00:00', '--job-id', '49865', '--raw', '--subdir', 'DAGS_FOLDER/Units_dag.py', '--cfg-path', '/tmp/tmpooiokac7', '--map-index', '6']
[2024-05-11T06:06:14.451+0000] {standard_task_runner.py:88} INFO - Job 49865: Subtask ETL_job
[2024-05-11T06:06:14.541+0000] {task_command.py:423} INFO - Running <TaskInstance: Units_statistics_DAG.ETL_job scheduled__2024-05-11T05:40:00+00:00 map_index=6 [running]> on host a09da322e808
[2024-05-11T06:06:14.730+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='abeer-araby' AIRFLOW_CTX_DAG_ID='Units_statistics_DAG' AIRFLOW_CTX_TASK_ID='ETL_job' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T05:40:00+00:00'
[2024-05-11T06:06:14.732+0000] {Units_dag.py:98} INFO - i: 60000, chunk: 10000
[2024-05-11T06:06:14.732+0000] {Units_dag.py:99} INFO - child token is::: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS5hZmFxeS5zYS9hdXRoL2xvZ2luX2FzIiwiaWF0IjoxNzE1NDA3MjA0LCJleHAiOjE3MTc5OTkyMDQsIm5iZiI6MTcxNTQwNzIwNCwianRpIjoiaTNzTEM4RjdIcDd4cTFYcyIsInN1YiI6IjVkNjNlNTFlMDNlZDUyOTJhNDJjMjRlNiIsInBydiI6IjI3MGVjZmM3ZWEzZWQ5MzdlYTg0OTM2MmEzYTUwOTEwYzZkOGNlNGYiLCJsb2dpbl9hc19pZCI6IjY1N2YwYWQ3M2Y5NzcyOTVjZjA1NTc2YSJ9.kOxio1WAsYuWr3AEJc62Tf7X6uro-1bIr-G83ul4ZOs
[2024-05-11T06:06:32.523+0000] {Units_dag.py:103} INFO - {'_id': '6330653326077657f723d5cd', 'icon': 'icons/A_10.png', 'driver_id': '', 'tailer_id': '', 'profile': {'vehicle_type': '', 'measurement_type': 'count', 'max_capacity': 0, 'vin': '', 'plate_number': '', 'start_operation': '', 'contract_milage': '', 'opening_milage': '', 'model': '', 'fuel_type': '91', 'year': 0, 'seats': 2}, 'device_password': '***', 'device_type': 'gps', 'gateway': False, 'name': '7741 - BSA', 'operation_code': '', 'device_gateway': '', 'business_types': {'waste': False, 'transportation': True, 'water': False}, 'imei': '869688059373276', 'sim_number': '+966830028895625', 'sim_serial': '996609821111331186', 'device_serial': '869688059373276', 'device': 'bce', 'user_id': '5ed3a92603ed527acb46a02c', 'created_by': '5e6655bf03ed52e1ab79d301', 'updated_at': '2024-04-18 11:18:59', 'created_at': '2022-09-25 17:26:59', 'custom_fields': [], 'creator': 'amr.ahmed', 'company': '', 'owner': 'al-musalam', 'last_update': {'dtt': 1715407540000, 'dts': 1715407553479, 'spd': 38, 'ang': 200, 'alt': 1480, 'chPrams': {'ePwrV': {'v': 27.651, 'cdt': 1715407540000}, 'di16': {'v': 1, 'cdt': 1713437822000}, 'di15': {'v': 0, 'cdt': 1664186992000}, 'rssi1': {'v': 78, 'cdt': 1715407540000}, 'di14': {'v': 1, 'cdt': 1715406552000}, 'di13': {'v': 0, 'cdt': 1714646348000}, 'di12': {'v': 0, 'cdt': 1713437822000}, 'di11': {'v': 0, 'cdt': 1713437822000}, 'di10': {'v': 0, 'cdt': 1713437822000}, 'di2': {'v': 1, 'cdt': 1715265552000}, 'di1': {'v': 1, 'cdt': 1715405842000}, 'ai4': {'v': 11476, 'cdt': 1715407540000}, 'di4': {'v': 0, 'cdt': 1714212852000}, 'di3': {'v': 0, 'cdt': 1713437822000}, 'di6': {'v': 0, 'cdt': 1714205352000}, 'di5': {'v': 1, 'cdt': 1715400914000}, 'lac1': {'v': 2587, 'cdt': 1715407192000}, 'protocol': {'v': 'bce', 'cdt': 1713437822000}, 'di8': {'v': 1, 'cdt': 1714754728000}, 'di7': {'v': 1, 'cdt': 1715400914000}, 'di9': {'v': 0, 'cdt': 1713437822000}, 'iPwrV': {'v': 4.156, 'cdt': 1715407510000}, 'cid1': {'v': 39891, 'cdt': 1715407488000}, 'odometer': {'v': 1134645014, 'cdt': 1715407540000}, 'spd': {'v': 38, 'cdt': 1715407540000}, 'sat': {'v': 10, 'cdt': 1715407540000}, 'hdop': {'v': 1, 'cdt': 1715405184000}, 'ta': {'v': 0, 'cdt': 1714205442000}, 'mcc1': {'v': 420, 'cdt': 1715152676000}, 'mnc1': {'v': 3, 'cdt': 1713254616000}}, 'prms': {'protocol': 'bce', 'spd': 38, 'sat': 10, 'hdop': 1, 'odometer': 1134645014, 'di16': 1, 'di15': 0, 'di14': 1, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 0, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 27.651, 'ai4': 11476, 'iPwrV': 4.156, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 2587, 'cid1': 39891, 'rssi1': 78}, 'devPrms': ['protocol', 'spd', 'sat', 'hdop', 'odometer', 'di16', 'di15', 'di14', 'di13', 'di12', 'di11', 'di10', 'di9', 'di8', 'di7', 'di6', 'di5', 'di4', 'di3', 'di2', 'di1', 'ePwrV', 'ai4', 'iPwrV', 'ta', 'mcc1', 'mnc1', 'lac1', 'cid1', 'rssi1'], 'old_params': {'protocol': 'bce', 'spd': 36, 'sat': 11, 'hdop': 1, 'odometer': 1130392380, 'di16': 1, 'di15': 0, 'di14': 1, 'di13': 0, 'di12': 0, 'di11': 0, 'di10': 0, 'di9': 0, 'di8': 1, 'di7': 1, 'di6': 0, 'di5': 1, 'di4': 0, 'di3': 0, 'di2': 1, 'di1': 1, 'ePwrV': 27.686, 'ai4': 13005, 'iPwrV': 4.156, 'ta': 0, 'mcc1': 420, 'mnc1': 3, 'lac1': 2587, 'cid1': 39891, 'rssi1': 82}, 'vLoc': 1, 'vCon': 1, 'ip': '109.83.6.31', 'rl': 0.3211, 'trl': 175503.7707, 'mdu': 30, 'tmdu': 10303340, 'eidl': 0, 'teidl': 12842404, 'fc': 0.038532, 'tfc': 11.994708, 'acc': 1, 'accOn': 24975176, 'accOff': 27268192, 'sdu': 0, 'tsdu': 0, 'lat': 21.499698638916016, 'lng': 40.488746643066406}, 'counters': {'odometer_type': 'gps', 'odometer': 175503.7705, 'engine_hours_type': 'acc', 'engine_hours': 24975176, 'last_acc': 1}, 'is_wasl_connected': 'Connected', 'iconUrl': 'https://api.afaqy.sa/images/units/icons/A_10.png', 'hasCCTV': False}
[2024-05-11T06:06:33.041+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk2.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-11T06:06:33.087+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk3.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-11T06:06:33.135+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py:399: SecurityWarning: Connecting to 'https://dbelk1.afaqy.local:9200' using TLS with verify_certs=False is insecure
  _transport = transport_class(

[2024-05-11T06:06:33.158+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-11T06:06:33.234+0000] {_transport.py:335} INFO - GET https://dbelk2.afaqy.local:9200/_cluster/health [status:200 duration:0.097s]
[2024-05-11T06:06:33.630+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk3.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-11T06:06:33.642+0000] {_transport.py:335} INFO - PUT https://dbelk3.afaqy.local:9200/units_statistics_***/_bulk [status:429 duration:0.029s]
[2024-05-11T06:06:33.643+0000] {_node_pool.py:249} WARNING - Node <Urllib3HttpNode(https://dbelk3.afaqy.local:9200)> has failed for 1 times in a row, putting on 1 second timeout
[2024-05-11T06:06:33.643+0000] {_transport.py:427} WARNING - Retrying request after non-successful status 429 (attempt 0 of 3)
[2024-05-11T06:06:33.644+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dbelk2.afaqy.local'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(

[2024-05-11T06:06:35.401+0000] {_transport.py:335} INFO - PUT https://dbelk2.afaqy.local:9200/units_statistics_***/_bulk [status:200 duration:1.758s]
[2024-05-11T06:06:35.673+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/Units_dag.py", line 111, in ETL_job
    Elk_client.elk_pushData(Globals.index_name,units_list_update)
  File "/opt/airflow/dags/units_statistics/elk_manager.py", line 69, in elk_pushData
    helpers.bulk(self.elk_client, docs_list, index=index_name, chunk_size=batch)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 274, in _process_bulk_chunk_success
    raise BulkIndexError(f"{len(errors)} document(s) failed to index.", errors)
elasticsearch.helpers.BulkIndexError: 2182 document(s) failed to index.
[2024-05-11T06:06:35.694+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=Units_statistics_DAG, task_id=ETL_job, map_index=6, execution_date=20240511T054000, start_date=20240511T060614, end_date=20240511T060635
[2024-05-11T06:06:35.716+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 49865 for task ETL_job (2182 document(s) failed to index.; 933427)
[2024-05-11T06:06:35.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-05-11T06:06:35.798+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
